---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ['forwarded_port', {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[xo-test]
      - recipe[xo]
      - recipe[xo::server-plugins]
    attributes:
      redisio:
        package_install: true
